### ISSUE TITLE
Issue snap 0.5  Elem.attr("fill")

### ISSUE THREAD

**Issue by pfx81** [adobe-webplatform/Snap.svg#503]
I get this error with the following code (with snap.svg.js 0.5):
```js
var s = Snap("#svg1"); 
var r = s.rect(100,100,100,100).attr({ stroke: '#123456', 'strokeWidth': 20, fill: 'red', 'opacity': 1 });

console.log(r.attr("fill"));
```

```
snap.svg.js:4123 Uncaught TypeError: Cannot read property '2' of null
    at Function.Snap.deurl (snap.svg.js:4123)
    at Element.<anonymous> (snap.svg.js:4511)
    at eve (snap.svg.js:111)
    at Element.attr (snap.svg.js:2276)
    at app.js:4
Snap.deurl @ snap.svg.js:4123
(anonymous) @ snap.svg.js:4511
eve @ snap.svg.js:111
Element.attr @ snap.svg.js:2276
(anonymous) @ app.js:4
```
Can someone confirm?

thank you

**Comment by DvdGiessen** [comment]
Confirmed, also ran into this issue. What's happening is that `deurl` is called for animations with a value which isn't an URL, throwing an exception.

[The `deurl` implementation](https://github.com/adobe-webplatform/Snap.svg/blob/master/src/attr.js#L35) added in 989b3f7c93b8f9e1c4f0c4b9f00960ad09d85da8 by @DmitryBaranovskiy. It is used in a few places without checking for the exception, for example with the fill property from the trace from above. It should probably catch the error in there and return some indicative value, or all calls should be argumented to check whether some value contains an URL first before trying to decode it.

This seems like a rather breaking issue, as it would break anything that doesn't use an URL in that property? As far as I can see at least the fill and stroke property animations seem to become instant breakers due to this bug, but I haven't checked all scenarios.

Minimal testcase:
v0.4.1 (before deurl) works: https://jsfiddle.net/wd4zbeh3/
v0.5.0 (with deurl) doesn't work: https://jsfiddle.net/ns4ygxss/

**Comment by DmitryBaranovskiy** [comment]
Fixed in 0.5.1.

**Comment by DvdGiessen** [comment]
The given minimal testcase still doesn't work with 0.5.1, this time throwing a `SyntaxError: 'rgb(170, 221, 85)' is not a valid selector`:
https://jsfiddle.net/df13LL5q/

In your commit you added some commented-out error catching which seems to be targeted at this issue: https://github.com/adobe-webplatform/Snap.svg/commit/bc579407fd2b61d531dd3d626600c812f3e65870#diff-02b6b27d8ebe8361ec2c5c64836b6825R901.

**Comment by DmitryBaranovskiy** [comment]
@DvdGiessen You are right. Generated versions had old content. Rebuilt and retagged.

**Comment by DvdGiessen** [comment]
@DmitryBaranovskiy I'm afraid you'll actually have to bump the patch version for npm to pick up the change; right now it is referencing the old version. See [their API output](http://registry.npmjs.com/snapsvg/0.5.1) (referencing the old commit id) and [their cached package file](https://registry.npmjs.org/snapsvg/-/snapsvg-0.5.1.tgz).

**Comment by DvdGiessen** [comment]
([CDNJS also hosts outdated dist files.](https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.5.1/snap.svg-min.js))

**Comment by kennygfunk** [comment]
Is this up on NPM yet? Still getting this error trying to animate a fill property.

**Comment by kennygfunk** [comment]
Tutorial still throws this as well: ```Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'rgb(186, 218, 85)' is not a valid selector.```

**Comment by kennygfunk** [comment]
@DmitryBaranovskiy any way you can get this fix up on npm?

**Comment by jpambrun** [comment]
I hate to be the one to bump, but the fix still didn't make it into npm.

**Comment by studio-marweb** [comment]
What about this issue? I see it still reproduces in 0.5.1 version using npm

**Comment by martingagne** [comment]
Any update on this? I am facing the same issue on 0.5.1 version using npm.

**Comment by kennsorr** [comment]
Hi, I'm also having this issue.  `.attr("fill")` works for me depending on how my SVG is loaded in. In the case where `.attr("fill")` does not work:

```
var icon = Snap(".aiIcon");
var paths = icon.selectAll("path");
console.log(paths[0].attr("fill");)    //returns 'undefined' (but should return the fill color)
paths[0].node.attributes.fill.value = "red";  //returns the fill color as .attr("fill") should
```

So if you want to change the fill of a path, use vanilla js and do:

```
paths[0].node.attributes.fill.value = hoverPink;
paths[0].node.attributes.fill.nodeValue = hoverPink;
paths[0].node.attributes.fill.textContent = hoverPink;
```

I've noticed there are a few different versions of Snap floating around (npm, cdns, donwloads) that are labeled 0.5.1, but are all different. Pretty frustrating
