### ISSUE TITLE
Issue snap 0.5 build: 2017-02-06  Elem.attr("fill")

### ISSUE THREAD

**Issue by pfx81** [adobe-webplatform/Snap.svg#504]
I get this new error with the following code (with snap.svg.js 0.5  build: 2017-02-06):

`var s = Snap("#svg1"); 
var r = s.rect(100,100,100,100).attr({ stroke: '#123456', 'strokeWidth': 20, fill: 'red', 'opacity': 1 });

console.log(r.attr("fill"));

Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'rgb(255, 0, 0)' is not a valid selector.
    at Snap (http://127.0.0.1:38233/test-snap-0.5/code/snap.svg.js:901:30)
    at Element.<anonymous> (http://127.0.0.1:38233/test-snap-0.5/code/snap.svg.js:4516:16)
    at eve (http://127.0.0.1:38233/test-snap-0.5/code/snap.svg.js:111:28)
    at Element.attr (http://127.0.0.1:38233/test-snap-0.5/code/snap.svg.js:2280:24)
    at http://127.0.0.1:38233/test-snap-0.5/code/app.js:4:15
Snap @ snap.svg.js:901
(anonymous) @ snap.svg.js:4516
eve @ snap.svg.js:111
Element.attr @ snap.svg.js:2280
(anonymous) @ app.js:4`

Can someone confirm?

thank you

**Comment by ThomasBrierley** [comment]
Is this with v0.5.1?

**Comment by DmitryBaranovskiy** [comment]
Fixed in 0.5.1

**Comment by cavanbecksmith** [comment]
I am still having this issue and am using version 0.5.1.
I am trying to animate a fill from a path using the following code 
el.animate({'fill': 'red'},1000);

**Comment by ibrierley** [comment]
Can confirm this http://jsfiddle.net/qywLcpqe/

**Comment by ibrierley** [comment]
Hmm that's using 0.5.0 from a cdn, just double checking

**Comment by ibrierley** [comment]
I note https://github.com/adobe-webplatform/Snap.svg/blob/master/dist/snap.svg.js has 0.5.1 written at the top, but 0.5.0 lower down for Eve and version. 

Not sure if that's correct, as I'm not so familiar with that side of things, but thought I would mention it in case.

**Comment by cavanbecksmith** [comment]
Thanks a million 👍  ! I was using the cdn link in my code and have just downloaded the latest distribution and works perfectly!

**Comment by ibrierley** [comment]
That's great. Missing piece of the puzzle for me, is how CDNs get their files in the first place.

**Comment by guirenpei** [comment]
it still happening ... in version 0.5.1 . how can i animate my fill color in svg?

**Comment by ibrierley** [comment]
You could probably build the fill manually, and use the Snap.animate( from,
to, function, duration, callback) method and use rgb() as an interim measure

Something like..

Snap.animate( [10,10,10],[20,30,40], function( val ) { el.attr('fill',
'rgb('+val[0]+','+val[1]+','+val[2]+')') }, 2000 );

**Comment by coolfe** [comment]
Quote this link is good： https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/snap.svg.js

 [I saw it here.](https://codepen.io/chriscoyier/pen/JoXbGN)

**Comment by cjgordon** [comment]
Confirm resolved in 0.5.1. As above there is confusing version on CDN that has filename 0.5.1 but is actually 0.5.0.
